### ISSUE TITLE
Missing Extras (menu) Descriptions 

### ISSUE THREAD

**Issue by EkoOne** [sergant210/AdminTools#16]
With AdminTools installed the descriptions under the Extras menu are missing from the listing (see screenshot). However, when AdminTools is uninstalled the descriptions return as expected.

![admintools_002](https://user-images.githubusercontent.com/1754223/50534241-8d980800-0aff-11e9-94db-82576523c342.png)

**Comment by sergant210** [comment]
Use the system setting "hide_component_description" to manage this behavior.
