### ISSUE TITLE
Проблема с политиками доступа

### ISSUE THREAD

**Issue by modxer** [sergant210/AdminTools#19]
Обнаружил, что если выставить ограниченные права юзеру (контент-менеджеру), то в консоли сыпятся ошибки. 

![5b8cbafcd3](https://user-images.githubusercontent.com/12284295/54647265-e221a280-4ab2-11e9-9b77-e0ec8c71c1e6.jpg)

Залез в плагин AdminTools и выставил проверку прав:

`if (($AdminTools instanceof AdminTools) and $modx->hasPermission('access_permissions') ) {}`

Ошибки пропали. Похоже компонент вне зависимости от доступа пытался управлять скрытыми элементами. С ошибками могут глючить js-скрипты. Например, не работает удаление файлов визуально. Изменения после перезагрузки страницы происходит.

**Comment by sergant210** [comment]
Принято.
