### ISSUE TITLE
Restricts element lists in Categories section

### ISSUE THREAD

**Issue by jmacdonald-spectacle** [sergant210/AdminTools#23]
Can't see list of elements in each category in category section. (featured added in MODX 2.7.0)

Tested in MODX 2.7.3. Uninstalled AdminTools and elements returned. Reinstalled and they disappeared again.

**Comment by sergant210** [comment]
Does your user have sudo permission?

**Comment by jmacdonald-spectacle** [comment]
Yes they do.

**Comment by sergant210** [comment]
Fixed.

**Comment by jmacdonald-spectacle** [comment]
Works great. Thanks!
