### ISSUE TITLE
Ошибочная проверка прав доступа

### ISSUE THREAD

**Issue by Mngatoff** [sergant210/AdminTools#24]
В плагине на событие OnLoadWebDocument запускается класс из папки services, а не model.
В этом файле в методе hasPermissions происходит строгая проверка userId через ===.
Так как данные при этом получены через modX::newQuery, в котором данные не типизованы, запрос возвращает поле principal в виде строки.
В результате проверка на доступ к странице обречена на провал.
При замене === на == все корректно. Строки 543 и 533
До последнего обновления, насколько я знаю, работало как надо.
![Снимок экрана 2020-09-22 в 01 23 28](https://user-images.githubusercontent.com/13394736/93827968-098e9800-fc73-11ea-8d17-c617c4b91ee9.png)
![Снимок экрана 2020-09-22 в 01 30 40](https://user-images.githubusercontent.com/13394736/93828053-4064ae00-fc73-11ea-94ad-8bbb94b2ee46.png)

**Comment by sergant210** [comment]
Исправил.
