### ISSUE TITLE
VersionX Integration

### ISSUE THREAD

**Issue by exside** [sergant210/AdminTools#4]
Would be awesome if we had the option to use data from VersionX instead of the cached element log! Could be automatic (if VersionX installed) or manual via system setting.

**Comment by sergant210** [comment]
May be. I don't use VersionX.

**Comment by exside** [comment]
what about querying the existing mangager_log table?

**Comment by sergant210** [comment]
Does it log elements changes&

**Comment by exside** [comment]
It does (now), but somehow feels a bit overkill to replicate existing logic =)

**Comment by sergant210** [comment]
> what about querying the existing mangager_log table?

done
