### ISSUE TITLE
Better persistence of favorites

### ISSUE THREAD

**Issue by exside** [sergant210/AdminTools#5]
Not sure about saving a users favorite elements into the cache, it's quite common to empty the cache manually when running into MODX weirdness, and if not careful (e.g. not deleting admintools cache folder) all users favorites will be gone...can already hear the complaints or more my complaint =)...so maybe it would be better to somehow save that data into the users profile, maybe an extended field or so?

EDIT: The main issue here seems persistence in general, no matter how hard I try, when I log out, my favorites/states are gone, this is simply because at the moment the whole stuff is happening (e.g OnManagerPageBeforeRender) modx doesn't know the user id yet (will be available from OnManagerLogin which comes a bit later on in the event chain) and thus cannot load the correct data (even if there, in the cache or whereever). It will simply load the data for userid = 0 (anonymous) user, which is always empty... Problem is, that we cannot modify the HTML in OnManagerLogin as the page is already rendered...no idea how to get that persistence with the current setup =/...like that the tool is unfortunately useless as you always loose your favorites...and that's a pitty, I really like the idea! An option could be to do the whole data loading / icon adding etc. trough a processor later on...or maybe I'm just tired and don't see the forest trough the trees...=)

if we ever find a solution to that, persistence in the user profile is easy:

```

    public function getFromProfile($key) {
        if ($this->modx->user->isAuthenticated('mgr')) {
            $profile = $this->modx->user->getOne('Profile');
            $fields = $profile->get('extended');

            if (isset($fields[$key])) {
                return $fields[$key];
            } else {
                return;
            }
        } else {
            return;
        }
    }

    public function saveToProfile($data, $key) {
        if ($this->modx->user->isAuthenticated('mgr')) {
            $profile = $this->modx->user->getOne('Profile');
            $fields = $profile->get('extended');

            $fields[$key] = $data;
            $profile->set('extended', $fields);
            if (!$profile->save()) {
                $this->modx->log(modX::LOG_LEVEL_ERROR, '[' . __METHOD__ . '] Could not save extended fields = ' . print_r($fields, 1));
            }
        }
    }
```

**Comment by sergant210** [comment]
It's a good idea. I'll think about it when I fully translate the text into Russian :)

**Comment by sergant210** [comment]
One of solutions - reread settings on "onManagerLogin". I keep thinking...

**Comment by exside** [comment]
I tried that, but how to pass it to extjs? we cannot modify the HTML code of the manager page after rendering...the user is getting "known" too late basically...I guess the proper way would be to load the data in the tree processor instead doing that on the OnManagerPageBeforeRender...there you would just add the JS/CSS files...

**Comment by sergant210** [comment]
>we cannot modify the HTML code of the manager page after rendering...

It's not complicated. There is only one thing - the user will see how the tree is changing after render. But it's not terrible. It will not happen often. Only when he logges in.

**Comment by sergant210** [comment]
Done. All user data save into his profile. Thank you for getFromProfile() and setToProfile() functions. They work good. :)
